### ISSUE TITLE
Some cookies not being set

### ISSUE THREAD

**Issue by efronbs** [efronbs/ProfileSharing#9]
Found bug where cookies with leading underscores are not being set.

**Comment by efronbs** [comment]
![image](https://cloud.githubusercontent.com/assets/9913519/19601549/c8ea8e8a-9777-11e6-8377-69718701991b.png)

Found one without a leading underscore

**Comment by efronbs** [comment]
Renamed, no corrolation

**Comment by sidstamm** [comment]
It appears that loadProfile has a parameter "profile" that is shadowing the global.  There may be other problems too.

See: https://github.com/efronbs/ProfileSharing/blob/master/JS/ProfileHandler.js#L119

**Comment by efronbs** [comment]
Solved: issue was incorrect use of substring resulted in bad URL being set.
